### PR TITLE
Adding DogeCash Support #2

### PR DESCRIPTION
**Pull request by Liquid369**
Try #2 for #220 

After bumping NBitcoin.Altcoin from 2.0.3 to 2.0.4 should build.

### CODE REVIEW

**Comment by Liquid369** [comment]
X on this is from not finding reference to DogeCash in NBitcoin.Altcoins

**Comment by Liquid369** [comment]
Last is now testMempoolAsync error, thats all that I see

**Comment by NicolasDorier** [comment]
conflicts, app veyor fail.

**Comment by Liquid369** [comment]
Resolved by catching up to master and bumping to NBitcoin 5.0.11

**Comment by NicolasDorier** [comment]
tests fail

**Comment by Liquid369** [comment]
10-4 ima reopen my testnet and ill bring this backup in a few days once I have time.

**Comment by Liquid369** [comment]
Deleted repo to start fresh since its been some time.

**Pull request closed without merging**
