### PR TITLE
Tracking addresses that already have balance #73

### PR DESCRIPTION
**Pull request by bazooka70**
Tracking addresses that already have balance.
PR in progress.

### CODE REVIEW

**Comment by bazooka70** [comment]
Done

**Comment by NicolasDorier** [comment]
Cool. Question though: Since you can get the txid from an external source, can this external source also provide you with the transactions ?

**Comment by bazooka70** [comment]
Well yes I suppose it can with much more efforts. for example blockchain info api gives you only tx block height so you need a nother api to get block hash. if blockchain info is unavailable I switch to other apis and so on. and each one of them is totally different. so constructing  Transactions miight be a pain in the ass.

**Comment by NicolasDorier** [comment]
Thanks a lot, I will likely change a bit this function to be able to pass the transactions, while still letting the capabilities of let them blank in case where the user has `txindex=1`.

**Comment by bazooka70** [comment]
Will I still be able to pass only tx ids?

**Comment by NicolasDorier** [comment]
Yes you will be able to pass only the tx ids.

**Comment by bazooka70** [comment]
Thanks man. That sounds awesome!

**Comment by NicolasDorier** [comment]
Sure I will make a PR so you can review.

**Comment by bazooka70** [comment]
Never mind the PR.  I was just curious at how the method parameters will look like... I'm sure you know way better than me at how to implement this.

**Comment by bazooka70** [comment]
OK, fair enough.

**Comment by bazooka70** [comment]
Any progress?

**Comment by NicolasDorier** [comment]
Sorry I did not had time, will do today

**Comment by NicolasDorier** [comment]
So it turns out, that we can remove the need of `-txindex` if we pass the `blockid` of each `txid`. Would it be fine for you?

**Comment by bazooka70** [comment]
Not sure I follow. Where do you see a `txindex` in my code?

**Comment by NicolasDorier** [comment]
Thanks for your help,

https://github.com/dgarage/NBXplorer/commit/88b11589d3c7b06c41b861d338207a9191c3007b

I just pushed package and docker. What you did will still work. (API is different though, but the inputs are the same if you have `-txindex`)

I extended a bit, and I batch RPC requests so it is faster.

I also test it.

**Comment by bazooka70** [comment]
Thank you! I have much to learn from you.
BTW, if the tx is not confirmed yet, you must use the `--txindex` anyway. or am I wrong?

**Comment by NicolasDorier** [comment]
I did not tried rescan on unconfirmed transaction. It might crash. That said this should not happen, because this is in general for old transaction.

**Comment by bazooka70** [comment]
@NicolasDorier , Just to be 100% clear: calling this methods multiple times (`Track` & `Rescan`), will make no harm? no duplicate data will be inserted to the DB?

PS: do you by chance know any DBreeze desktop explorer?

**Comment by NicolasDorier** [comment]
@bazooka70 no DBreeze explorer, but no worry, it should not insert twice. You can try.

**Comment by bazooka70** [comment]
@NicolasDorier, yes I have tested and it *seems* there are no duplicates, and everything really works like a charm! :100:  
Does the DBreeze ignore inserting a duplicate key(s)? or there is an exception which you internally ignore/suppress?

**Comment by bazooka70** [comment]
OK thanks! moving to production... :)

**Comment by bazooka70** [comment]
BTW, the old versions had `chain-stripped.dat` but now it keeps `chain-slim.dat`.

What will happen if if update the NBXplorer server on a machine which already was running old version of NBXplorer and has `chain-stripped.dat`?

**Comment by NicolasDorier** [comment]
don't worry about this data, it is just an optimization for starting nbxplorer faster. Not important data.

**Comment by bazooka70** [comment]
OK, NBXplorer deleted it for me :)
Running on production. so far so good! :1st_place_medal:

**Pull request closed without merging**
