### PR TITLE
Added Azure Service Bus support

### PR DESCRIPTION
**Pull request by chriswhellams**
- Added support for Azure Service Bus message broker as IHostedService. Supports both Queues and Topics.

- Uses same serialization as WebSocket

- Moved ToTransactionResult from MainController to Utils to aid re-use

- Added NewEventBase abstract base class with helper methods for Json conversion, updated NewEvent classes to derive from base.

- Added 2 Unit tests for Azure Service Bus and static TestConfig.cs to supply config settings

- Extended config settings to support Azure Service Bus config

- Removed some unused using statements

- Updated readme.md with information on Azure Service Bus Message Broker and how to configure

- All unit tests passing when active Service Bus connection string supplied.

- Azure service bus tests fail with no connection string message when connection string unavailable

- Rebased from latest Main branch, no merge conflicts

### CODE REVIEW

**Comment by chriswhellams** [comment]
@NicolasDorier All requested changes - except hardcoding queue / topic names are implemented. No merge conflicts .

**Comment by NicolasDorier** [comment]
You can dramatically simplify this code, Topic and Queue have a common interface `ISenderClient`.
Which mean that you don't have to have `_queueTran` and `_queueTopic` instead you can have one `_queueSender`.

**Comment by NicolasDorier** [comment]
Do you want I cleanup or you want to try to do it?

**Comment by vineeth7858** [comment]
No don't cleanup

**Comment by chriswhellams** [comment]
@NicolasDorier  ooh, good find ! Msft have made the client libs for Azure Service Bus somewhat confusing as they have different versions for framework and core and docs are outdated or specific to one of the client implementations.  Let me take a look at this now and I can see how it works and I'll make the change and test everything again.

**Comment by chriswhellams** [comment]
@NicolasDorier I looked at ISenderClient, I am not really seeing how this simplifies the code as it appears to be just an abstraction interface that derives from ITopicClient, IQueueClient and IMessageSender and provides the "lowest common denominator" from those interfaces - which is pretty much SendAsync. It still looks like you need to use concrete classes such as QueueClient and TopicClient . Queues and Topics are not the same thing so I don't think you can use a combined _queueSender. I cannot find any worked examples from Google of this being used anywhere - which is often a sign nobody is using it ! I am somewhat cautious / nervous of using Msft features that lack examples / documentation due to the fact Msft seem not to test much these days and let the community do that instead - the Msft PM responsible for service bus also seems to be far more interested in Event Hubs these days - which is also a warning sign for me of something un-loved.

Ok - you could make something fancy and inject in the concrete classes and use a single method to handle things but that will add complexity.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.core.isenderclient?view=azure-dotnet

https://azure.microsoft.com/en-us/blog/author/juconway/

If you want to switch to ISenderClient it's your call, I'm not going to do that unless there is an obvious benefit or I have totally missed something. Have I totally missed something ? ;-)

**Comment by NicolasDorier** [comment]
Ok, I'll take a look.

**Comment by NicolasDorier** [comment]
My apologies, I completely forgot about it, working on it now.

**Comment by NicolasDorier** [comment]
I took the freedom to cleanup your code on ac905261cbbdd6bc37822fa513a8f67e0255ddaa .

Basically, you were copying 4 times the same code for Queue/Topic, Transaction/Block, which was not good. The tests were not using assert, making it hard to debug.

I also prepared the way for RabbitMQ support to which @sigHash seems interested it https://github.com/dgarage/NBXplorer/issues/85 by abstracting azure specific stuff into a `IBrokerClient` interface fairly easy to implement.

**Comment by chriswhellams** [comment]
Many thanks for taking the PR and for improving.

**Pull request merged**
