### PR TITLE
Change Dbreeze to DBTrie

### PR DESCRIPTION
**Pull request by NicolasDorier**
This remove the use of DBReeze with the rewrite of it in a more efficient way.

Should fix https://github.com/dgarage/NBXplorer/issues/272

Please @farukterzioglu can you try on your data? Please backup the db directory in the NBXplorer datadir and see:
1. Does it fix the issue?
2. Does the RAM seems OK.

Don't run this in production yet, I still have to do something.
(Not creating one file for each new transaction coming)

### CODE REVIEW

**Comment by NicolasDorier** [comment]
@farukterzioglu @joemphilips @junderw please try this on a backup of something representative of your actual production workload. This PR has all the changes I wanted to include. Performance issues on large wallet should be gone, as almost everything is cached in RAM.

**Comment by NicolasDorier** [comment]
The rewrite of DBreeze has been done on [this project](https://github.com/NicolasDorier/DBTrie/).

**Comment by NicolasDorier** [comment]
Got a crash on start on one of my prod box. Checking.

**Comment by NicolasDorier** [comment]
Fixed the crash. This should be ready. Tried on one of my deployment, works like a charm.

**Comment by NicolasDorier** [comment]
I tried on another of my box with a few thousands of transaction. This is definitely faster, however NBX now take way more RAM than before.

**Comment by NicolasDorier** [comment]
To decrease memory usage, I am limiting the amount of data cached by default.
If you have big machine with big wallet set `highmemory=1` or `--highmemory` by command line.

Please I need you feedback. If it is still too slow, there is another thing I can do, but I prefer to not do as it blow up the RAM even more.

**Comment by joemphilips** [comment]
Thanks for you work! Our dev-ops team is now testing. Probably we can give you a feedback in few days.

**Comment by junderw** [comment]
why not make the parameter be in MB like Bitcoin Core?

**Comment by NicolasDorier** [comment]
@junderw because I don't have time to make is so customizable at the db level.

**Comment by farukterzioglu** [comment]
I will test it soon with production data on our backup setup (just came back from vacation)
thanks for your work.

**Comment by NicolasDorier** [comment]
So my tests on enumeration of 7000 transactions with "highmemory" takes 90ms instead of 2 seconds. I might make it possible to fine tunes the RAM and limiting as @junderw suggested. Might try later next week.

**Comment by NicolasDorier** [comment]
I confirm, the slow down was caused by the topological sort in my case.

**Comment by NicolasDorier** [comment]
@junderw I changed the `highmemory` to `dbcache` (in MB)

**Comment by NicolasDorier** [comment]
Just managed to improve query perf even more. For 7000 tx, I have gone from 2s to 50ms if enough cache.
If there is a bottleneck now, it is in the code of NBXplorer rather than the database.

**Comment by NicolasDorier** [comment]
@farukterzioglu probably fixed the issue on windows as well. NBXplorer was sluggish on my dev machine (maybe hundred time slower than linux for inserts), now it is as fast as linux.

**Comment by farukterzioglu** [comment]
> @farukterzioglu probably fixed the issue on windows as well. NBXplorer was sluggish on my dev machine (maybe hundred time slower than linux for inserts), now it is as fast as linux.

Ok, thanks Nicolas. I will probably test it today on Linux, will update the results.

**Comment by farukterzioglu** [comment]
On the first run got an exception as;
```
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: DASH,LTC,BTC
info: Configuration:  DBCache: 50 MB
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: DASH,LTC,BTC
info: Configuration:  DBCache: 50 MB
info: Explorer:       BTC: Defragmented transaction table (152.48 MB saved)
info: Explorer:       Migrating 73569 legacy tables...
Unhandled exception. System.InvalidOperationException: No page available to evict from cache
   at DBTrie.Storage.Cache.PagePool.NewPage(Int32 pageNumber)
   at DBTrie.Storage.CacheStorage.FetchPage(Int32 p)
   at DBTrie.Storage.CacheStorage.Write(Int64 offset, ReadOnlyMemory`1 input)
   at DBTrie.Storage.StorageExtensions.WriteToEnd(IStorage storage, ReadOnlyMemory`1 input)
   at DBTrie.TrieModel.LTrieNode.WriteNewValue(ReadOnlyMemory`1 key, ReadOnlyMemory`1 value)
   at DBTrie.TrieModel.LTrieNode.SetExternalValue(Byte label, ReadOnlyMemory`1 key, ReadOnlyMemory`1 value)
   at DBTrie.TrieModel.LTrieNode.SetValue(Nullable`1 linkLabel, ReadOnlyMemory`1 key, ReadOnlyMemory`1 value)
   at DBTrie.TrieModel.LTrie.SetValue(ReadOnlyMemory`1 key, ReadOnlyMemory`1 value)
   at DBTrie.Table.Insert(ReadOnlyMemory`1 key, ReadOnlyMemory`1 value)
   at NBXplorer.Repository.MigrateSavedTransactions(CancellationToken cancellationToken) in /NBXplorer/NBXplorer/Repository.cs:line 1259
   at NBXplorer.Repository.MigrateSavedTransactions(CancellationToken cancellationToken) in /NBXplorer/NBXplorer/Repository.cs:line 1253
   at NBXplorer.RepositoryProvider.StartAsync(CancellationToken cancellationToken) in /NBXplorer/NBXplorer/Repository.cs:line 98
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at NBXplorer.Program.Main(String[] args) in /NBXplorer/NBXplorer/Program.cs:line 60
```

on the second run, same exception with only difference;
```
info: Explorer:       Migrating 62147 legacy tables...
```

and 3. run got and exception as;
```
info: Explorer:       Migrating 51596 legacy tables...
Unhandled exception. System.InvalidOperationException: MoveNext is not called
   at DBTrie.Table.DeferredAsyncEnumerable.get_InternalEnumerator()
   at DBTrie.Table.DeferredAsyncEnumerable.DisposeAsync()
   at NBXplorer.Repository.MigrateSavedTransactions(CancellationToken cancellationToken) in /NBXplorer/NBXplorer/Repository.cs:line 1253
   at NBXplorer.RepositoryProvider.StartAsync(CancellationToken cancellationToken) in /NBXplorer/NBXplorer/Repository.cs:line 98
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at NBXplorer.Program.Main(String[] args) in /NBXplorer/NBXplorer/Program.cs:line 60
```

trying with only BTC....

**Comment by NicolasDorier** [comment]
thanks a lot. Looking into it.

**Comment by NicolasDorier** [comment]
For the first exception, you can fix it with bigger dbcache.
For the second one, making the fix.

**Comment by NicolasDorier** [comment]
@farukterzioglu the two exception should be fixed now, try again.

**Comment by farukterzioglu** [comment]
Got the latest commit, then got this exception;
```
info: Configuration:  Supported chains: DASH,LTC,BTC
info: Configuration:  DBCache: 50 MB
info: Explorer:       BTC: Defragmented transaction table (0 bytes saved)
info: Explorer:       LTC: Defragmented transaction table (0 bytes saved)
info: Explorer:       Migrating 36915 legacy tables...
Unhandled exception. System.InvalidOperationException: No page available to evict from cache
   at DBTrie.Storage.Cache.PagePool.NewPage(Int32 pageNumber)
   at DBTrie.Storage.CacheStorage.FetchPage(Int32 p)
   at DBTrie.Storage.CacheStorage.Read(Int64 offset, Memory`1 output)
   at DBTrie.TrieModel.LTrie.OpenFromStorage(IStorage storage, MemoryPool`1 memoryPool)
   at DBTrie.TrieModel.LTrie.OpenOrInitFromStorage(IStorage storage, MemoryPool`1 memoryPool)
   at DBTrie.Table.GetTrie()
   at DBTrie.Table.DeferredAsyncEnumerable.MoveNextAsync()
   at NBXplorer.Repository.MigrateSavedTransactions(CancellationToken cancellationToken) in /NBXplorer/NBXplorer/Repository.cs:line 1255
   at NBXplorer.Repository.MigrateSavedTransactions(CancellationToken cancellationToken) in /NBXplorer/NBXplorer/Repository.cs:line 1255
   at NBXplorer.RepositoryProvider.StartAsync(CancellationToken cancellationToken) in /NBXplorer/NBXplorer/Repository.cs:line 98
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at NBXplorer.Program.Main(String[] args) in /NBXplorer/NBXplorer/Program.cs:line 60

```

I will try with increased db cache size

**Comment by NicolasDorier** [comment]
dammit...

**Comment by farukterzioglu** [comment]
When I increase dbCache to 500mb, it completed migration for all of them, now it is processing the blocks since I stopped it. 
Will test query response times...

**Comment by NicolasDorier** [comment]
Fixing stuff around. Will be ready in a few hour.

**Comment by NicolasDorier** [comment]
@farukterzioglu should be good now.
If you can retest the migration on your huge amount of table, I would be very happy. I want to make sure it does not crash when I push that on master.

**Comment by farukterzioglu** [comment]
Re-started the migration with not-migrated data from one hour ago backup. It still goes on since 15min ago...

```
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: DASH,LTC,BTC
info: Configuration:  DBCache: 50 MB
info: Explorer:       Defragmenting transaction tables...
info: Explorer:       Defragmentation succeed, 225.74 MB saved
info: Explorer:       Applying migration if needed, do not close NBXplorer...
```

**Comment by farukterzioglu** [comment]
With latest commit, migration from scratch completed successfully 👍   
It migrated 129697 tables with default settings.

But it looks like it takes long time, couldn't calculate the time, bored from waiting and take a walk at outside :) I think it took about 1 hour. 

But results looks like awesome, it is faster at least 10x times, ~60s vs ~6s. I can share more result after I activate it on production.

**Comment by NicolasDorier** [comment]
@farukterzioglu thank you and is it on the windows machine? 6s still seem slow to me

**Comment by NicolasDorier** [comment]
@farukterzioglu I would have a solution to drop to 3s, but that would require another migration. I don't like migration as if it fail, things can get nasty. But I think one day I will do.

**Comment by NicolasDorier** [comment]
@farukterzioglu can you test a last time on this commit ? The migration should be quite fast.

**Comment by farukterzioglu** [comment]
> @farukterzioglu thank you and is it on the windows machine? 6s still seem slow to me

It is on linux with machine spec;
Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz
4 cpu
8 GB ram
Azure standart ssd (NBX directory is on OS disk)
bitcoin core on different machine

I will start another migration from scratch, after that I will compare the result, also after pruning.

**Comment by farukterzioglu** [comment]
image

There must be something wrong or different on me. It is 2 hours and still going on. 
At first run all 4 cpus were at ~%50, but now look like nothing being used.

**Comment by farukterzioglu** [comment]
After pruning BTC/LTC/DASH, getting 1350 BTC txs at 5s and 470 utxo at 4s (w/ curl on the same machine.)

**Comment by NicolasDorier** [comment]
thanks a lot.
Migration taking time sucks... I guess I will just put proper feedback about the speed.

**Comment by NicolasDorier** [comment]
@farukterzioglu I think if you pruned the wallet and restart again, defragmentation will free up space, making queries faster.

**Comment by farukterzioglu** [comment]
After restart;
```
info: Explorer:       Defragmenting transaction tables...
info: Explorer:       Defragmentation succeed, 226.76 MB saved
```
Response time slightly decreased (~0.5s)

I don't know if it is related to defragmentation, but we have some small utxos we never spend since the first start of NBX.
So there is always some transactions we don't spend nor we can prune.

image

**Comment by farukterzioglu** [comment]
Directed some traffic after migration (for some queries that safe for production)
Here are the results.

image

**Comment by NicolasDorier** [comment]
@farukterzioglu btw there is a parameter in nbxplorer to ignore output below some dust. Though I don't think you can clean them up from now.

**Comment by farukterzioglu** [comment]
> @farukterzioglu btw there is a parameter in nbxplorer to ignore output below some dust. Though I don't think you can clean them up from now.

Yes, set it for a moment ago, but old ones is stayed here, it doesn't worth the fee to spend them.

**Comment by NicolasDorier** [comment]
ping @junderw any news of testing on your side?

**Comment by NicolasDorier** [comment]
@farukterzioglu you might want to increase the dbcache for your case, it might speed up.

**Pull request merged**
