### PR TITLE
[Add] DogeCash Support

### PR DESCRIPTION
**Pull request by Liquid369**
This PR builds successfully and I have not gotten any issues during the test cases.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
I don't think it can work, if I remember DogeCash is not supported by NBitcoin anymore because it was breaking NBitcoin.Altcoins for some reason and nobody fixed it.

**Comment by Liquid369** [comment]
There was a recent PR https://github.com/MetacoSA/NBitcoin/pull/792
Fixing invalid hexstring error and is still supported.

Then submitted a PR yesterday as well to update versions
https://github.com/MetacoSA/NBitcoin/pull/918

**Comment by Liquid369** [comment]
If there is some errors still I will recheck through today

**Comment by NicolasDorier** [comment]
as you can see dogecash crash it all

**Comment by NicolasDorier** [comment]
maybe related, maybe not. NBitcoin's AltcoinNetworkSets.cs Dogecash is commented. It was commented because it was crashing in similar way.

**Pull request closed without merging**
