### PR TITLE
UTXO returns correct DerivationFeature

### PR DESCRIPTION
**Pull request by Ashish81**
`UTXO.feature` not returning correctly , it always returns the Deposit. It is fixed, please review

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Thanks a lot, but can you instead assign the `DerivationStrategy` in the GetUTXOs method of the controller ? I would like to keep the DTO as dumb as possible.

**Comment by Ashish81** [comment]
Did you mean assign the `DerivationFeature ` in the GetUTXOs?? 

> instead assign the `DerivationStrategy `in the GetUTXOs

**Comment by NicolasDorier** [comment]
Perfect thanks!

**Comment by Ashish81** [comment]
You're welcome

**Comment by Ashish81** [comment]
Wondering how to get UTXOs of an address (or keypath)? One way i guess is to compare the scriptpubkey of the UTXOChanges.  Wont it make sense to add a parameter in GetUTXos method ?? for fast retrieval

**Pull request merged**
