### PR TITLE
Allow SOCKSv5 configuration for P2P connection

### PR DESCRIPTION
**Pull request by NicolasDorier**
Can use `NBXPLORER_SOCKS_ENDPOINT`, `NBXPLORER_SOCKS_USER`, `NBXPLORER_SOCKS_PASSWORD` to configure a SocksV5 proxy to connect to the P2P network.

### CODE REVIEW

**Comment by farukterzioglu** [comment]
@NicolasDorier is it `NBXPLORER_SOCKSENDPOINT` or `NBXPLORER_SOCKS_ENDPOINT`.   
we were able to see `Socks ...` logs when we configure it with `NBXPLORER_SOCKSENDPOINT`.

**Comment by farukterzioglu** [comment]
We can send http requests with curl through the same socks proxy, we believe there isn't any issue with connecting to the proxy.   
The error we got is : https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/Socks/SocksHelper.cs#L173

`SocksException("Invalid BIND address in connect reply")`

**Comment by vishwabmc** [comment]
Hello @NicolasDorier, from the code. I see the env to be set is `NBXPLORER_socksendpoint` and that is the one I have used in the setup.  When I started the pod, I could see NBX recognising it as it put these traces onto the console. 

```
info: [2023-07-27 07:49:02Z] Configuration: Network: Testnet
info: [2023-07-27 07:49:02Z] Configuration: Socks endpoint: socks5:1080
info: [2023-07-27 07:49:02Z] Configuration: Supported chains: BTC
```

**Comment by NicolasDorier** [comment]
Can you show me the full logs of what happen after those logs?

**Comment by NicolasDorier** [comment]
@farukterzioglu note that the SOCKS configuration isn't for the RPC connection but only for P2P.

**Comment by farukterzioglu** [comment]
For now, we have;
```
info: [2023-07-27 07:49:02Z] Configuration: Data Directory: /opt/app-root/data
info: [2023-07-27 07:49:02Z] Configuration: Configuration File: /opt/app-root/data/TestNet/settings.config
info: [2023-07-27 07:49:02Z] Configuration: Creating configuration file
info: [2023-07-27 07:49:02Z] Configuration: Network: Testnet
info: [2023-07-27 07:49:02Z] Configuration: Socks endpoint: socks5:1080
info: [2023-07-27 07:49:02Z] Configuration: Supported chains: BTC
info: [2023-07-27 07:49:02Z] Configuration: Network: Testnet
info: [2023-07-27 07:49:02Z] Configuration: Socks endpoint: socks5:1080
info: [2023-07-27 07:49:02Z] Configuration: Supported chains: BTC
info: [2023-07-27 07:49:02Z] NBXplorer.DatabaseSetup: Postgres services activated
Hosting environment: Production
Content root path: /opt/app-root/app/
Now listening on: http://0.0.0.0:32838
```

it doesn't show handshake logs, we can get more logs in the meanwhile.   

So far, we only configured NBXplorer with `NBXPLORER_socksendpoint` environment variable.

**Comment by vishwabmc** [comment]
> @farukterzioglu note that the SOCKS configuration isn't for the RPC connection but only for P2P traffic.
> If you configured to route RPC calls, it's why it doesn't work.

@NicolasDorier Thanks.. I was thinking that it's a replacement to `https_proxy`. Is it not ?.. I ask since you say it's only for `p2p`. What may be the proxy solution for `https` ?.  Thanks

**Comment by NicolasDorier** [comment]
@vishwabmc Most of the time SOCKS is needed because the P2P traffic isn't HTTP and so some corporate policy forbid such traffic, HTTP is usually just fine and don't need a SOCKS proxy.

If you really need SOCKS for HTTP, you can add it to NBX by making a PR. (using separate configuration `NBXPLORER_RPCSOCKS*`).

It shouldn't be too hard, the HTTP stack of dotnet have native support for SOCKS.

You can inspire yourself from my code on btcpayserver:

https://github.com/btcpayserver/btcpayserver/blob/19d360a54374f13014f28239ae4a4c444594fc33/BTCPayServer/Services/Socks5HttpClientHandler.cs#L8

**Comment by farukterzioglu** [comment]
```
info: [2023-08-07 10:09:18Z] Configuration: Data Directory: /opt/app-root/data
info: [2023-08-07 10:09:18Z] Configuration: Configuration File: /opt/app-root/data/TestNet/settings.config
info: [2023-08-07 10:09:18Z] Configuration: Creating configuration file
info: [2023-08-07 10:09:18Z] Configuration: Network: Testnet
info: [2023-08-07 10:09:18Z] Configuration: Socks endpoint: socks5:1080
info: [2023-08-07 10:09:18Z] Configuration: Supported chains: BTC
info: [2023-08-07 10:09:18Z] Configuration: Network: Testnet
info: [2023-08-07 10:09:18Z] Configuration: Socks endpoint: socks5:1080
info: [2023-08-07 10:09:18Z] Configuration: Supported chains: BTC
info: [2023-08-07 10:09:19Z] NBXplorer.DatabaseSetup: Postgres services activated
info: [2023-08-07 10:09:20Z] NBXplorer.DatabaseSetup: Execute script 001.Migrations...
info: [2023-08-07 10:09:20Z] NBXplorer.DatabaseSetup: Execute script 002.Model...
info: [2023-08-07 10:09:20Z] NBXplorer.DatabaseSetup: Execute script 003.Legacy...
info: [2023-08-07 10:09:20Z] NBXplorer.DatabaseSetup: Execute script 004.Fixup...
info: [2023-08-07 10:09:20Z] NBXplorer.DatabaseSetup: Execute script 005.ToBTCFix...
info: [2023-08-07 10:09:20Z] NBXplorer.DatabaseSetup: Execute script 006.GetWalletsRecent2...
info: [2023-08-07 10:09:20Z] NBXplorer.DatabaseSetup: Execute script 007.FasterSaveMatches...
info: [2023-08-07 10:09:20Z] NBXplorer.DatabaseSetup: Execute script 008.FasterGetUnused...
info: [2023-08-07 10:09:20Z] NBXplorer.DatabaseSetup: Execute script 009.FasterGetUnused2...
info: [2023-08-07 10:09:20Z] NBXplorer.DatabaseSetup: Execute script 010.ChangeEventsIdType...
info: [2023-08-07 10:09:20Z] NBXplorer.DatabaseSetup: Execute script 011.FixGetWalletsRecent...
info: [2023-08-07 10:09:20Z] NBXplorer.DatabaseSetup: Execute script 012.PerfFixGetWalletsRecent...
info: [2023-08-07 10:09:20Z] NBXplorer.DatabaseSetup: Execute script 013.FixTrackedTransactions...
info: [2023-08-07 10:09:20Z] NBXplorer.DatabaseSetup: Execute script 014.FixAddressReuse...
info: [2023-08-07 10:09:20Z] NBXplorer.DatabaseSetup: Execute script 015.AvoidWAL...
Hosting environment: Production
Content root path: /opt/app-root/app/
Now listening on: http://0.0.0.0:32838
Application started. Press Ctrl+C to shut down.
fail: [2023-08-07 10:09:21Z] NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 0 seconds
NBitcoin.Socks.SocksException: Invalid BIND address in connect reply
   at NBitcoin.Socks.SocksHelper.Handshake(Socket socket, EndPoint endpoint, NetworkCredential credentials, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.ConnectNode(CancellationToken token, Boolean forceRestart) in /opt/app-root/src/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 256
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /opt/app-root/src/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 80
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /opt/app-root/src/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 59
fail: [2023-08-07 10:09:21Z] NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 5 seconds
NBitcoin.Socks.SocksException: Invalid BIND address in connect reply
   at NBitcoin.Socks.SocksHelper.Handshake(Socket socket, EndPoint endpoint, NetworkCredential credentials, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.ConnectNode(CancellationToken token, Boolean forceRestart) in /opt/app-root/src/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 256
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /opt/app-root/src/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 80
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /opt/app-root/src/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 59

```
@NicolasDorier fyi

**Comment by farukterzioglu** [comment]
and socks proxy printing logs as;

```
2023/08/07 10:07:22 Start listening proxy service on port 1080
2023/08/07 10:09:20 [INFO] socks: Connection from allowed IP address: x.x.x.x
2023/08/07 10:09:21 [INFO] socks: Connection from allowed IP address: x.x.x.x

```

**Comment by farukterzioglu** [comment]
With another proxy, it worked.   
We were running the proxy https://github.com/serjs/socks5-server   

There may be a compatibility issue. Is there any requirement for the supported Socks5 server.

**Pull request merged**
