### PR TITLE
add altcoin support for althash 

### PR DESCRIPTION
**Pull request by denuoweb**
The tests will succeed when NBXplorer updates to newest NBitcoin version 5.0.74 as of 2/23/2021

### CODE REVIEW

**Comment by NicolasDorier** [comment]
can you update nbitcoin then?

**Comment by denuoweb** [comment]
> can you update nbitcoin then?

I think only you can update nbitcoin. I included another Nbitcoin pull request to bump the nbitcoin.altcoin version and I made another commit on nbxplorer to switch to the new nbitcoin.altcoin version.

**Comment by NicolasDorier** [comment]
did

**Comment by denuoweb** [comment]
> did

the AppVeyor build test fails because  "No connection could be made because the target machine actively refused it. 127.0.0.1:5672"

This is the failed task:
CanSendRabbitMqNewBlockEventMessage
https://github.com/dgarage/NBXplorer/blob/45819a7c47f50bb1d716479a2bd9aa1eef076039/NBXplorer.Tests/UnitTest1.cs#L1392

**Pull request merged**
