### PR TITLE
Feathercoin Support

### PR DESCRIPTION
**Pull request by ChekaZ**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
nice, can you tell me where are the binaries to feather coin ? I need it to make it testable

**Comment by TrezarCoin** [comment]
https://github.com/FeatherCoin/Feathercoin/releases

**Comment by ChekaZ** [comment]
https://github.com/FeatherCoin/Feathercoin/releases

**Comment by NicolasDorier** [comment]
hey, can you add FeatherCoin to to https://github.com/MetacoSA/NBitcoin.TestFramework/blob/master/NBitcoin.TestFramework/WellknownNodeDownloadData.cs ? This would allow me to run unit tests against it.

**Comment by ChekaZ** [comment]
I've added Feathercoin Support for NBitcoin.TestFramekwork

**Comment by NicolasDorier** [comment]
nice, I merged on TestFramework, do you want I update it on NBXplorer so you can try to run the tests on it?

**Comment by ChekaZ** [comment]
Would be great.

**Comment by NicolasDorier** [comment]
Ok, try it now I updated:

Change https://github.com/dgarage/NBXplorer/blob/master/NBXplorer.Tests/ServerTester.cs#L55

and https://github.com/dgarage/NBXplorer/blob/master/NBXplorer.Tests/ServerTester.cs#L59 then you should be able to run the tests on FeatherCoin.

I won't test this myself, so try it, and let me know how it goes.

**Comment by NicolasDorier** [comment]
So, does the tests pass?

**Comment by ChekaZ** [comment]
Working on it, Ive updated the https://github.com/MetacoSA/NBitcoin.TestFramework/blob/master/NBitcoin.TestFramework/WellknownNodeDownloadData.cs  and did a PR, could you please merge it?

**Comment by NicolasDorier** [comment]
@ChekaZ it is already merged and package already updated on nbxplorer.

**Comment by ChekaZ** [comment]
I made a new PR 4h ago, it has slight fixes in it.

**Comment by NicolasDorier** [comment]
I am making a big refactoring on NBitcoin which will make altcoin testing easier. Will take your changes.

**Comment by NicolasDorier** [comment]
will you update this PR now that Feathercoin is inside NBitcoin.Altcoins?

**Pull request closed without merging**
