### PR TITLE
Add Terracoin Support

### PR DESCRIPTION
**Pull request by TheSin-**
This is the initial request to add Terracoin. I made this fork a while ago and tested it but got side tracked, I just merged in all the upstream changes but haven't tested it since. I wanted to make the request before I forgot, I'll be testing this week but looking at the PR I can't see things breaking.

### CODE REVIEW

**Comment by TheSin-** [comment]
Build failures are due to not being in NBitcoin yet, but that request is in as well, perhaps I should have waiting to submit this one, I apologies if that is the protocol I must have missed it.

https://github.com/MetacoSA/NBitcoin/pull/798

**Comment by TheSin-** [comment]
NBitcoin PR was just accepted, going to focus on this one and make sure that tests pass next.

**Comment by TheSin-** [comment]
Terracoin have version control built in, so tests fail because of this.  I need a message in the version message.

Currently NBXplorer sends

```
send version message: version 70208, blocks=101, us=[::0, peer=8
```

and I NEEDS to be, the "Terracoin Core" can be what ever, but the 0.12.2.4 needs to be in the slashes and right after a :

```
send version message: /Terracoin Core:0.12.2.4/: version 70208, blocks=101, us=[::0, peer=8
```

is there a var I can set currently to make this happen so I can run the tests?

**Comment by NicolasDorier** [comment]
There is no "message" in the version payload (https://en.bitcoin.it/wiki/Protocol_documentation#version)

**Comment by TheSin-** [comment]
```
Version message:
 62 EA 00 00                                                                   - 60002 (protocol version 60002)
 01 00 00 00 00 00 00 00                                                       - 1 (NODE_NETWORK services)
 11 B2 D0 50 00 00 00 00                                                       - Tue Dec 18 10:12:33 PST 2012
 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 FF FF 00 00 00 00 00 00 - Recipient address info - see Network Address
 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 FF FF 00 00 00 00 00 00 - Sender address info - see Network Address
 3B 2E B3 5D 8C E6 17 65                                                       - Node ID
 0F 2F 53 61 74 6F 73 68 69 3A 30 2E 37 2E 32 2F                               - "/Satoshi:0.7.2/" sub-version string (string is 15 bytes long)
 C0 3E 03 00                                                                   - Last block sending node has is block #212672
```

0F 2F 53 61 74 6F 73 68 69 3A 30 2E 37 2E 32 2F                               - "/Satoshi:0.7.2/" sub-version string (string is 15 bytes long)

Which is part of the version call

It's okay though I'm going to rework my code as you are correct I'm misusing this field.

**Comment by NicolasDorier** [comment]
This is the "user agent". It should not be empty, normally NBX set one.

**Comment by TheSin-** [comment]
I agree, no idea why it is in the tests :\

**Comment by TheSin-** [comment]
Oddly enough I get a bunch of failed tests, but it seems the tests aren't respecting the Terracoin config from NBitcoin where segwit is set to false.

https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin.Altcoins/Terracoin.cs#L357

```
[xUnit.net 00:00:32.65]     NBXplorer.Tests.UnitTest1.CanGenerateWallet [FAIL]
                                                                                  X NBXplorer.Tests.UnitTest1.CanGenerateWallet [2s 363ms]
  Error Message:
   NBXplorer.Models.NBXplorerException : Segwit is not supported, please explicitely set scriptPubKeyType to Legacy
  Stack Trace:
     at NBXplorer.ExplorerClient.ParseResponse[T](HttpResponseMessage response) in /Users/justin/Devel/cvsroot/NBXplorer/NBXplorer.Client/ExplorerClient.cs:line 637
   at NBXplorer.ExplorerClient.SendAsync[T](HttpMethod method, Object body, String relativePath, Object[] parameters, CancellationToken cancellation) in /Users/justin/Devel/cvsroot/NBXplorer/NBXplorer.Client/ExplorerClient.cs:line 601
   at NBXplorer.Tests.UnitTest1.CanGenerateWallet() in /Users/justin/Devel/cvsroot/NBXplorer/NBXplorer.Tests/UnitTest1.cs:line 3215
--- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
 2020-03-09 1:33:42 PM +00:00 :Configuration:   Network: Regtest
 2020-03-09 1:33:42 PM +00:00 :Configuration:   Supported chains: TRC
 2020-03-09 1:33:42 PM +00:00 :Configuration:   TRC: Testing RPC connection to http://127.0.0.1:11532/
 2020-03-09 1:33:42 PM +00:00 :Configuration:   TRC: RPC connection successful
 2020-03-09 1:33:42 PM +00:00 :Configuration:   TRC: Full node version detected: 120205
 2020-03-09 1:33:42 PM +00:00 :Configuration:   TRC: Trying to connect via the P2P protocol to trusted node (127.0.0.1:11886)...
 2020-03-09 1:33:42 PM +00:00 :Explorer:   TRC: TCP Connection succeed, handshaking...
 2020-03-09 1:33:42 PM +00:00 :Explorer:   TRC: Handshaked
 2020-03-09 1:33:42 PM +00:00 :Configuration:   TRC: Loading chain from node
 2020-03-09 1:33:42 PM +00:00 :Explorer:   TRC: Loading chain...
 2020-03-09 1:33:42 PM +00:00 :Explorer:   TRC: Chain loaded
 2020-03-09 1:33:42 PM +00:00 :Explorer:   TRC: NBXplorer is correctly whitelisted by the node
 2020-03-09 1:33:42 PM +00:00 :Configuration:   TRC: Height: 101
 2020-03-09 1:33:42 PM +00:00 :Explorer:   TRC: Current Index Progress not found, start syncing at height 101
 2020-03-09 1:33:42 PM +00:00 :Explorer:   TRC: Starting scan at block 101
 2020-03-09 1:33:42 PM +00:00 :Events:   TRC: Node state changed: NotStarted => NBXplorerSynching
 2020-03-09 1:33:42 PM +00:00 :Events:   TRC: Node state changed: NBXplorerSynching => Ready
 2020-03-09 1:33:43 PM +00:00 :Events:   TRC: New block e9d7cb76f62a0db5c9a410dee41a269a661c2808a1973266d47ec585b0b8c87f (102)
 2020-03-09 1:33:43 PM +00:00 :Tests:   Let's try default parameters
 2020-03-09 1:33:43 PM +00:00 :Explorer:   TRC: Closed connection with node
```

**Comment by NicolasDorier** [comment]
@TheSin- are they the only reason? if so we can merge I think.

**Comment by TheSin-** [comment]
@NicolasDorier there are 17 errors, I'll get the different version of the errors, but I believe they are all due to segwit, I'm just heading to work right now but I'll run it once there and post the summary.

**Pull request merged**
