### PR TITLE
Add Monacoin.

### PR DESCRIPTION
**Pull request by cryptcoin-junkey**

### CODE REVIEW

**Comment by cryptcoin-junkey** [comment]
＠NicolasDorier Thanks for merging. And I wish the new NBXplorer.Client (1.0.2.8) was deployed to Nuget repo...

**Comment by NicolasDorier** [comment]
Already done, but nuget.org seems having issues right now :( (I pushed like 1 H ago 2 different packages and they still do not show up)

**Comment by NicolasDorier** [comment]
It has been referenced by btcpay

**Comment by cryptcoin-junkey** [comment]
I confirmed that my docker build for BTCPayServer also done with success this morning. I'm going to deploy the image to my K8s cluster. Thank you!

**Pull request merged**
