### PR TITLE
Add support for Chaincoin

### PR DESCRIPTION
**Pull request by fellowserf**

### CODE REVIEW

**Comment by fellowserf** [comment]
Any idea if this will get into the next build?
Thx

**Comment by NicolasDorier** [comment]
have you tested it by following what is said on https://github.com/dgarage/NBXplorer#how-to-add-support-to-my-altcoin

Because if the tests don't pass, it is not useful for you to have this merged.

**Comment by fellowserf** [comment]
Thanks Nicolas
NBXplorer.Tests.UnitTest1.CanScanUTXOSet did fail.
Have asked the community why this is not supported in the current version, before I proceed further..

**Comment by NicolasDorier** [comment]
@fellowserf is it the only test failing? might jsut be they don't support this feature at RPC level.

**Comment by fellowserf** [comment]
Getting 5 fails in total
1. CanScanUTXOSet
2. CanRescanFullyIndexedTransaction - Dep 1
3. CanSendAzureServiceBusNewBlockEventMessage
4 .CanSendAzureServiceBusNewTransactionEventMessage
5. ShowRBFedTransaction

Will see if I can setup Azure to at least confirm 3 and 4.  Everything else is good.

**Comment by NicolasDorier** [comment]
Seems good enough.

**Pull request merged**
