### PR TITLE
Add RPC Client Proxy

### PR DESCRIPTION
**Pull request by Kukks**
This let's you use nbx as a direct proxy to the node rpc.

### CODE REVIEW

**Comment by Kukks** [comment]
@NicolasDorier removed all the unneeded logic. Should be good to go

**Comment by NicolasDorier** [comment]
It should not be on by default, there is a security implication.
Can you add a global configuration switch to enable this feature and default to false.

**Comment by Kukks** [comment]
@NicolasDorier  done

**Comment by Kukks** [comment]
oops did not mean to close

**Pull request merged**
