### PR TITLE
Update and add Polis Network

### PR DESCRIPTION
**Pull request by cronos-polis**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
I just updated the package, can you revert your change on the csproj files?

**Comment by cronos-polis** [comment]
Done.

**Comment by NicolasDorier** [comment]
Test POLIS by changing https://github.com/dgarage/NBXplorer/blob/master/NBXplorer.Tests/ServerTester.Environment.cs and running the tests. Then comment so people interested in testing your coin can do it.

**Comment by cronos-polis** [comment]
Thanks. Will test Regtest later. We need to launch it first.
Mainnet works good I already setup btcpayserver with it.

**Pull request merged**
