### PR TITLE
WIP:Feature/mass transit

### PR DESCRIPTION
**Pull request by Kukks**
This expands the new ASB support to also have 2 MassTransit brokers support:
ASB via MassTransit
RabbitMQ via MassTransit

Missing from this:

- [x] Integrate into `BrokerHostedService`
- [x] Fetch config from the `ExplorerConfiguration`
- [ ] Unit Test MassTransit brokers

### CODE REVIEW

**Comment by Kukks** [comment]
yup, forgot to stage those :)

**Comment by chriswhellams** [comment]
Nice, we used MT in a previous job. It's a good framework.

**Comment by NicolasDorier** [comment]
love it

**Comment by NicolasDorier** [comment]
can you provide a docker-compose which fireup rabbitmq so we can test ?

**Comment by NicolasDorier** [comment]
`blockbroker.0.broadcasttype=send` make no sense for asb

**Comment by Kukks** [comment]
Added it in the regtest docker @NicolasDorier

**Comment by NicolasDorier** [comment]
I don't understand the `broadcasttype` concept, what is it?

**Comment by Kukks** [comment]
Publish is when the message is sent to all subscribers and send is when it is sent to a queue and processed by one subscriber. 
Maybe I got the asb terminology mixed up a bit though? 
https://www.maldworth.com/2015/10/27/masstransit-send-vs-publish/

**Comment by NicolasDorier** [comment]
it works with azure queue as well? But you need to set to send right?

**Comment by Kukks** [comment]
Yeah, so send is the equivalent of a queue and publish is for the topic

**Comment by NicolasDorier** [comment]
It seems good to me, can you update the doc?

**Comment by Kukks** [comment]
Updated readme and the default config creator. I had to remove the asb arguments as it is a bit too complex for that now. Just needs tests now. :)

**Comment by NicolasDorier** [comment]
still need tests

**Comment by Kukks** [comment]
Yes, started adding some a few days ago, will finish up soon

**Comment by Kukks** [comment]
@NicolasDorier  I added in some tests but whenever I try to test the `ServerTester.Create()` seems to never finish executing?

**Comment by NicolasDorier** [comment]
@Kukks it means you are not properly disposing something

**Comment by Kukks** [comment]
It seems to be something with the `NodeBuilder` as it never gets past that?

**Comment by Kukks** [comment]
@NicolasDorier  Do you have any docs somewhere on how to run the tests? I haven't been able to get past this issue

**Comment by NicolasDorier** [comment]
It is because it download bitcoin core so the first run might take a while.

**Comment by Kukks** [comment]
I need to revisit this  on a separate pull request, but maybe not at all since nobody seems to actually need it.

**Pull request closed without merging**
