### PR TITLE
Add Argoneum

### PR DESCRIPTION
**Pull request by osnwt**
Add Argoneum support to NBitcoin, NBXplorer and BTCPayServer

These changes depend on NBitcoin support ( see PR https://github.com/MetacoSA/NBitcoin/pull/844) and runtime tests may fail unless NBitcoin is updated.

### CODE REVIEW

**Comment by osnwt** [comment]
As expected.

```
NBXplorerNetworkProvider.Argoneum.cs(12,29): error CS0234: The type or namespace name 'Argoneum' does not exist in the namespace 'NBitcoin.Altcoins' (are you missing an assembly reference?) [C:\projects\nbxplorer\NBXplorer.Client\NBXplorer.Client.csproj]
NBXplorerNetworkProvider.Argoneum.cs(21,29): error CS0234: The type or namespace name 'Argoneum' does not exist in the namespace 'NBitcoin.Altcoins' (are you missing an assembly reference?) [C:\projects\nbxplorer\NBXplorer.Client\NBXplorer.Client.csproj]
```

**Comment by NicolasDorier** [comment]
you can bump NBitcoin.Altcoins to test

**Comment by osnwt** [comment]
Done!

**Comment by rockstardev** [comment]
@osnwt Rebase required

**Comment by osnwt** [comment]
Of course, since a month has passed.
Rebased.

**Comment by osnwt** [comment]
Could I ask you to publish a new version?

We have other PRs delayed (https://github.com/btcpayserver/btcpayserver/pull/1504) since they require AGM support which currently is not yet available in last published NBXplorer assembly.

Thanks

**Comment by NicolasDorier** [comment]
done

**Comment by sierracoin-team** [comment]
Thanks! But I have a runtime issue.

btcpayserver references NBXplorer.Client 3.0.15, which is a part of NBXplorer 2.1.31 (and 2.1.30 too). When I try to build a docker image of btcpayserver, seems it includes an old NBXplorer into the build since it's Client is of version 3.0.15 for a long time. Of course, btcpayserver crashes at runtime since it has no AGM support in the old NBXplorer.Client.

The build system works properly since there is no requirement to use NBXplorer 2.1.31, the only requirement is to use (possibly, old) NBXplorer.Client 3.0.15.

Perhaps, version of NBXplorer.Client should also be increased. Otherwise normally built btcpayserver has issues at runtime, exactly what I wanted to avoid.

Can you give any suggestions how to handle this properly? I see only one way - to bump the version of NBXplorer.Client, but I am not a C# developer, so maybe there are other options.

PS. Sooner or later, NBXplorer will be updated everywhere, so it will not be a problem. But strictly speaking, the whole dependency chain doesn't look proper right now. I think that's incorrect, is it?

**Comment by osnwt** [comment]
Thanks! But I have a runtime issue.

btcpayserver references NBXplorer.Client 3.0.15, which is a part of NBXplorer 2.1.31 (and 2.1.30 too). When I try to build a docker image of btcpayserver, seems it includes an old NBXplorer into the build since it's Client is of version 3.0.15 for a long time. Of course, btcpayserver crashes at runtime since it has no AGM support in the old NBXplorer.Client.

The build system works properly since there is no requirement to use NBXplorer 2.1.31, the only requirement is to use (possibly, old) NBXplorer.Client 3.0.15.

Perhaps, version of NBXplorer.Client should also be increased. Otherwise normally built btcpayserver has issues at runtime, exactly what I wanted to avoid.

Can you give any suggestions how to handle this properly? I see only one way - to bump the version of NBXplorer.Client, but I am not a C# developer, so maybe there are other options.

PS. Sooner or later, NBXplorer will be updated everywhere, so it will not be a problem. But strictly speaking, the whole dependency chain doesn't look proper right now. I think that's incorrect, is it?

**Comment by NicolasDorier** [comment]
I just pushed new client for NBXplorer.Client.

**Comment by NicolasDorier** [comment]
NBXplorer.Client and NBXplorer versioning are completely separate.

**Comment by osnwt** [comment]
Yes, they are. But new currencies are being added to NBXplorer.Client. Its version still is 3.0.15 in the repository (changed on May 24th) and was not changed after AGM addition (added on May 29th).

You increased version of NBXplorer (https://github.com/dgarage/NBXplorer/commit/b33af198867f6db4b310031a4ee6a673fa28e9f9), but version of NBXplorer.Client was not changed after this PR merge. That's the issue.

**Comment by NicolasDorier** [comment]
it did https://www.nuget.org/packages/NBXplorer.Client

**Comment by osnwt** [comment]
Wow, I see it there, but this repo still has [3.0.15](https://github.com/dgarage/NBXplorer/blob/master/NBXplorer.Client/NBXplorer.Client.csproj#L6).

That's why I had questions...

**Comment by NicolasDorier** [comment]
just bump the version in your pr

**Comment by osnwt** [comment]
Done yesterday, thanks!

**Pull request merged**
